# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20170825_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='user',
        ),
    ]
